name: Bomb TV
options:
  bundleIdPrefix: uk.co.nathanwong.giantbomb

packages:
  Nuke:
    url: https://github.com/kean/Nuke.git
    from: 8.4.0
  PromiseKit:
    url: https://github.com/mxcl/PromiseKit
    from: 6.13.0
  PMKFoundation:
    url: https://github.com/PromiseKit/Foundation.git
    from: 3.3.4

targets:
  Bomb TV:
    type: application
    platform: tvOS
    deploymentTarget: 13.0
    sources: [Bomb TV]

    attributes:
      ProvisioningStyle: Manual

    configFiles: 
      Debug: Bomb TV/Configs/debug.xcconfig
      Release: Bomb TV/Configs/release.xcconfig

    dependencies:
      - target: BombAPI
        embed: true
      - target: TopShelf
        embed: true
      - sdk: TVUIKit.framework
      - package: Nuke

    scheme:
      testTargets:
        - UnitTests
        - UITests

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: uk.co.nathanwong.giantbomb.tv

  BombAPI:
    type: framework
    platform: tvOS
    sources: [BombAPI]
    configFiles:
      Debug: BombAPI/Configs/debug.xcconfig
      Release: BombAPI/Configs/release.xcconfig
    dependencies:
      - package: PromiseKit
        embed: false
      - package: PMKFoundation
        embed: false

  TopShelf:
    type: app-extension
    platform: tvOS
    sources: [TopShelf]

    dependencies: 
      - target: BombAPI
      - sdk: TVServices.framework

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: uk.co.nathanwong.giantbomb.tv.TopShelf

  UnitTests:
    type: bundle.unit-test
    platform: tvOS
    sources: [Bomb TVTests]
    dependencies:
      - target: Bomb TV

  UITests:
    type: bundle.ui-testing
    platform: tvOS
    sources: [Bomb TVUITests]
    dependencies:
      - target: Bomb TV