name: Bomb TV

configFiles:
  Debug: Configs/debug.xcconfig
  Release: Configs/release.xcconfig

options:
  bundleIdPrefix: uk.co.nathanwong.giantbomb

packages:
  Nuke:
    url: https://github.com/kean/Nuke.git
    from: 9.1.1

targets:
  Bomb TV:
    type: application
    platform: tvOS
    deploymentTarget: 15.0
    sources: [Bomb TV]

    attributes:
      ProvisioningStyle: Manual

    configFiles: 
      Debug: Bomb TV/Configs/debug.xcconfig
      Release: Bomb TV/Configs/release.xcconfig

    dependencies:
      - target: BombAPI
        embed: true
      - target: TopShelf
        embed: true
      - sdk: TVUIKit.framework
      - package: Nuke

    entitlements:
      path: Bomb TV/Bomb TV.entitlements
      properties:
        com.apple.security.application-groups:
          - group.uk.co.nathanwong.giantbomb.tv

    scheme:
      testTargets:
        - UnitTests
        - UITests

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: uk.co.nathanwong.giantbomb.tv

  BombAPI:
    type: framework
    platform: tvOS
    sources: [BombAPI]
    configFiles:
      Debug: BombAPI/Configs/debug.xcconfig
      Release: BombAPI/Configs/release.xcconfig

  TopShelf:
    type: app-extension
    platform: tvOS
    sources: [TopShelf]

    configFiles:
      Debug: TopShelf/Configs/debug.xcconfig
      Release: TopShelf/Configs/release.xcconfig

    dependencies: 
      - target: BombAPI
      - sdk: TVServices.framework

    entitlements:
      path: TopShelf/TopShelf.entitlements
      properties:
        com.apple.security.application-groups:
          - group.uk.co.nathanwong.giantbomb.tv

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: uk.co.nathanwong.giantbomb.tv.TopShelf

  UnitTests:
    type: bundle.unit-test
    platform: tvOS
    sources: [Bomb TVTests]
    dependencies:
      - target: Bomb TV

  UITests:
    type: bundle.ui-testing
    platform: tvOS
    sources: [Bomb TVUITests]
    dependencies:
      - target: Bomb TV