name: Bomb TV
options:
  bundleIdPrefix: uk.co.nathanwong

packages:
  Nuke:
    url: https://github.com/kean/Nuke.git
    from: 8.4.0
  PromiseKit:
    url: https://github.com/mxcl/PromiseKit
    from: 6.13.0
  PMKFoundation:
    url: https://github.com/PromiseKit/Foundation.git
    from: 3.3.4

targets:
  Bomb TV:
    type: application
    platform: tvOS
    deploymentTarget: 13.0
    sources: [Bomb TV]

    configFiles: 
      Debug: Bomb TV/Configs/debug.xcconfig
      Release: Bomb TV/Configs/release.xcconfig

    dependencies:
      - target: BombAPI
      - sdk: TVUIKit.framework
      - package: Nuke

  BombAPI:
    type: framework.static
    platform: tvOS
    sources: [BombAPI]
    configFiles:
      Debug: BombAPI/Configs/debug.xcconfig
      Release: BombAPI/Configs/release.xcconfig
    dependencies:
      - package: PromiseKit
        embed: true
      - package: PMKFoundation
        embed: true

  UnitTests:
    type: bundle.unit-test
    platform: tvOS
    sources: [Bomb TVTests]
    dependencies:
      - target: Bomb TV

  UITests:
    type: bundle.ui-testing
    platform: tvOS
    sources: [Bomb TVUITests]
    dependencies:
      - target: Bomb TV