default_platform(:ios)

platform :ios do
  desc "Validate that everything is working as it should be"
  lane :test do
    scan
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "appstore", readonly: true)
    build_app(scheme: "Bomb TV")
    upload_to_testflight(app_platform: "appletvos")
  end
end
